### ISSUE TITLE
Setup instructions don't work on Ubuntu Linux

### ISSUE THREAD

**Issue by jamesnvc** [algernon/Akela#101]
I followed the setup instructions in the documentation; it works fine on OS X, but when using Ubuntu, when I open Arduino IDE, I get a bunch of dialogs saying that "library Aklea-* cannot be used", saying that it has an invalid character.

![screenshot-2016-12-15_10 07 16_est-05 00_1481814436](https://cloud.githubusercontent.com/assets/38405/21229085/5b1256d8-c2ae-11e6-922a-90adde78d755.png)

The IDE does open and I can see the examples, but if I try to "verify" them, I get an error saying "KeyboardioFirmware.h: No such file or directory".

I also seem to be lacking the ability to select Keyboardio under the hardware menu, although it is symlinked in place.

**Comment by algernon** [comment]
Which version of the Arduino IDE are you using?

**Comment by jamesnvc** [comment]
Apparently "2:1.0.5+dfsg2-4"...I believe that was just what I got by doing `sudo apt install arduino` on Ubuntu 16.04

![screenshot-2016-12-15_10 16 18_est-05 00_1481814978](https://cloud.githubusercontent.com/assets/38405/21229426/8db51ef8-c2af-11e6-8e80-55c60dee7a83.png)

**Comment by jamesnvc** [comment]
I am trying uninstalling that & getting the version from the website.

**Comment by jamesnvc** [comment]
Okay, looks like it works fine with the latest version from the website!
