### ISSUE TITLE
Implement a KLE -> Akela/Model01 transpiler

### ISSUE THREAD

**Issue by algernon** [algernon/Akela#30]
Start from a known KLE layout, and from the JSON, create the appropriate firmware source. Should be in JavaScript (or a language that targets JS), so this can be put on a static site.

The hard part is the layers, and special keys (layer toggle, momentary layer switch, one-shot layer, one-shot modifier, etc). The current idea is to use colors, and naming convention:

- One-shot keys should have a *blue* background.
- Modifiers use their normal names, or symbols.
- Layers are named `L<...>``, eg: `L<NAV>`.
- Shades of colors make it possible to differentiate between layers.
- Layer toggle has *red* background.
- Momentary layer has a *green* background.
- Legend colors match the layer colors.

So for example, we could have a one-shot `Shift` by turning the keys background color to blue. A momentary layer toggle that goes to layer `Foo` is a green `L<Foo>` key, and all the legends that have the exact same shade of green will be on the `Foo` layer.

**Comment by algernon** [comment]
Hm. Colors may not be the best, at least for layers, because legends would be hard to distinguish.

So... one-shot modifiers are any modifier which are colored? Any color other than white would work, since we identify modifiers by their label, and they are either normal, or one-shot.

As for layers, color should not matter, we'll use the label:
 - L*foo* would be a layer toggle.
 - ML*foo* would be momentary.
 - OS*foo* would be one-shot.

This would allow much more freedom with colors. Another option, which would allow even more freedom, would be to use a hidden (same legend color as the background) label part on the modifier to signal its one-shotness. Eg, the front print could be white-on-white `OSM` text.

This could be done for layers too... but should be an option, in all honesty.

**Comment by obra** [comment]
I'd probably shy away from using colors as semantic information. 

I wonder if a suffix character might be easier to understand. Like using ! to indicate toggles, @ to indicate momentary and ? to indicate one shot..or something. Those characters aren't the best choices.

**Comment by algernon** [comment]
Hmmm. The suffix char idea sounds good. Shorter and more expressive than the prefixes, and the layer indicating prefix can be dropped too.

I may even go a step further, and treat one of the three as default (probably momentary), so it would work even without a suffix. What do you think?

**Comment by obra** [comment]
I think you want some prefix or delimiter around things that aren't supposed to be regular keypresses.

Treating momentary as the default seems very reasonable.

**Comment by algernon** [comment]
Hrm... having thought more about it overnight, you're right: if I want to add macros and other special things later, a prefix will, indeed, be needed. But with the `!@?` postfixes, an `L` for layers is enough.

**Comment by algernon** [comment]
Created a [new project][magic-wings] for this purpose, and summarized the current plan [there][mw:1]. Further work will be done there, as I don't want to tie it to neither Akela, nor to the Model01.

[magic-wings]: https://github.com/algernon/magic-wings
[mw:1]: https://github.com/algernon/magic-wings/issues/1
