### ISSUE TITLE
ErgoDox EZ / Teensyduino port

### ISSUE THREAD

**Issue by algernon** [algernon/Akela#48]
It would be nice to run the same firmware on both the Model 01 and my current ErgoDox EZ. However, the Teensyduino lacks PluggableUSB, so the Arduino HID library will not work with it. So, I either need to port PluggableUSB to the Teensyduino, or write a HID library for the USB stuff Teensyduino has.

This port can only happen once I have a Model 01 at home, because developing and testing with the same keyboard is neither practical, nor wise, or scalable.

**Comment by eltang** [comment]
I have a Planck which I'm not using and I'd be happy to help you test with it.

**Comment by algernon** [comment]
I might make use of that offer, if time allows. Thanks! :)

**Comment by algernon** [comment]
This is obsolete, the project changed focus, and will not be a complete firmware, but plugins for KeyboardioFirmware instead.
